version: 2
jobs:
  test:
    working_directory: ~/content_translator
    docker:
      # Keep in sync with the version in elixir_buildpack.config
      - image: circleci/elixir:1.7.2
      - image: circleci/redis:3.2.12-alpine

    steps:
      - type: checkout
      - run: mix local.rebar --force
      - run: mix local.hex --force
      - run: mix deps.get
      - run: script/ci/pipeline.sh tests "script/ci/tests.sh"

  deploy:
    working_directory: ~/content_translator
    docker:
      - image: circleci/ruby:2.5.0
    steps:
      - type: checkout
      - run: script/ci/pipeline.sh deploy_production "script/ci/deploy.sh $HEROKU_APP_NAME"

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
