version: 2
jobs:
  test:
    working_directory: ~/content_translator
    docker:
      # Keep in sync with the version in elixir_buildpack.config
      - image: circleci/elixir:1.7.2
      - image: circleci/redis:3.2.12-alpine

    steps:
      - checkout:
          name: "Checking out code"
      - run:
          name: "Setting up package manager"
          command: mix local.rebar --force && mix local.hex --force
      - run:
          name: "Getting deps"
          command: mix deps.get
      - run:
          name: "Compiling code"
          command: MIX_ENV=test mix compile
      - run:
          name: "Running tests"
          command: script/ci/pipeline.sh tests "script/ci/tests.sh"

  deploy:
    working_directory: ~/content_translator
    docker:
      - image: circleci/ruby:2.5.0

    steps:
      - checkout:
          name: "Checking out code"
      - run:
          name: "Deploying to production"
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              script/ci/pipeline.sh deploy_production "script/ci/deploy.sh $HEROKU_APP_NAME"
            fi

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
